<?php
declare(strict_types=1);
/**
 * Affiliate page stub — auto-generated by tools/sync_affiliate_page_stubs.php
 */
require_once dirname(__DIR__, 2) . '/includes/affiliate_page_render.php';
reps_affiliate_try_dispatch('seven-aff');
