#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * Generate public/a/{slug}/index.php stubs for active sales seats.
 * Pattern: Empanada Option C (pretty paths without nginx rewrites).
 *
 *   php tools/sync_affiliate_page_stubs.php
 */

$root = dirname(__DIR__);
require_once $root . '/public/includes/affiliate_pages.php';

if (!defined('REPS_DASH_LOADED')) {
    define('REPS_DASH_LOADED', true);
}
require_once $root . '/public/dashboard/includes/config.php';
require_once $root . '/public/dashboard/includes/db.php';

$pdo = repsDashDb();
$rows = $pdo->query(
    "SELECT username FROM users WHERE role = 'sales' AND is_active = 1 ORDER BY username COLLATE NOCASE"
)->fetchAll(PDO::FETCH_ASSOC) ?: [];

$slugs = [];
foreach ($rows as $row) {
    $slug = strtolower(trim((string) ($row['username'] ?? '')));
    if (reps_affiliate_slug_valid($slug)) {
        $slugs[] = $slug;
    }
}

$stubRoot = $root . '/public/a';
if (!is_dir($stubRoot) && !mkdir($stubRoot, 0755, true) && !is_dir($stubRoot)) {
    fwrite(STDERR, "Cannot create {$stubRoot}\n");
    exit(1);
}

$want = [];
$written = [];
foreach ($slugs as $slug) {
    $want[$slug] = true;
    $dir = $stubRoot . '/' . $slug;
    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
        fwrite(STDERR, "skip mkdir {$dir}\n");
        continue;
    }
    $escaped = var_export($slug, true);
    $php = <<<PHP
<?php
declare(strict_types=1);
/**
 * Affiliate page stub — auto-generated by tools/sync_affiliate_page_stubs.php
 */
require_once dirname(__DIR__, 2) . '/includes/affiliate_page_render.php';
reps_affiliate_try_dispatch({$escaped});

PHP;
    $file = $dir . '/index.php';
    $prev = is_file($file) ? (string) file_get_contents($file) : '';
    if ($prev !== $php) {
        file_put_contents($file, $php);
        $written[] = $slug;
    }
}

// Remove stale stubs (not in active sales list / reserved)
$removed = [];
foreach (glob($stubRoot . '/*', GLOB_ONLYDIR) ?: [] as $dir) {
    $slug = strtolower(basename($dir));
    if (isset($want[$slug])) {
        continue;
    }
    $index = $dir . '/index.php';
    if (is_file($index)) {
        unlink($index);
    }
    if (is_dir($dir) && count(scandir($dir) ?: []) <= 2) {
        rmdir($dir);
        $removed[] = $slug;
    }
}

echo json_encode([
    'ok' => true,
    'slugs' => array_keys($want),
    'written' => $written,
    'removed' => $removed,
    'urls' => array_map(static function (string $s): array {
        return [
            'slug' => $s,
            'subdomain' => reps_affiliate_canonical_url($s),
            'path' => reps_affiliate_path_url($s),
        ];
    }, array_keys($want)),
], JSON_PRETTY_PRINT) . "\n";
